name: replay_identification
channels:
- defaults
- conda-forge
- edeno
dependencies:
- "python>=3.4"
- numpy
- numba
- scipy
- statsmodels
- scikit-learn
- matplotlib
- xarray
- dask
- spectral_connectivity
- regularized_glm
- patsy
- jupyter
- nb_conda
- setuptools
- pytest
- pytest-cov
- coveralls
