name: replay_identification
channels:
- defaults
- conda-forge
- edeno
dependencies:
- "python>=3.6"
- numpy
- numba
- scipy
- statsmodels
- scikit-learn
- matplotlib
- networkx
- xarray
- holoviews
- dask
- tqdm
- ipywidgets
- nodejs
- track_linearization
- spectral_connectivity
- regularized_glm
- patsy
- jupyter
- jupyterlab
- nb_conda
- setuptools
- pytest
- pytest-cov
- coveralls
- joblib
