name: replay_identification
channels:
- defaults
- conda-forge
- edeno
dependencies:
- "python>=3.4"
- numpy
- numba
- scipy
- statsmodels
- matplotlib
- xarray
- spectral_connectivity
- patsy
- jupyter
- nb_conda
- setuptools
- pytest
- pytest-cov
- coveralls
