name: replay_identification
channels:
- defaults
- conda-forge
- edeno
dependencies:
- numpy
- numba
- scipy
- scikit-learn
- matplotlib
- xarray
- dask
- track_linearization
- spectral_connectivity
- regularized_glm
- cupy
- tqdm
- jupyter
- jupyterlab
- nb_conda
- setuptools
- joblib
- pytest
- pytest-cov
- coveralls
