---
name: "tagged-release"

on:
  push:
    branches:
      - master
      - main
    tags:
      - "v*"  # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: contains(github.ref, 'tags')
    steps:
      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
          tag_prefix: v

      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"
