---
name: "tagged-release"

on:
  push:
    branches:
      - master
      - main
    tags:
      - "v*"  # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    if: contains(github.ref, 'tags')
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: null
          prerelease: false
          files: |
            LICENSE.md
